name: Dispatch
on:
  workflow_dispatch:
    inputs:
      issue:
        description: "Issue number to update after apply"
        required: true
        type: number

jobs:
  apply:
    runs-on: ubuntu-latest

    if: ${{ github.ref_name == 'prod' && github.ref_protected && github.actor == 'anuraaga' }}

    environment: prod
    steps:
      - uses: actions/checkout@v4
        with:
            ref: prod
      - run: |
          echo ${{ vars.DATA }}
          echo ${{ github.event.sender.login }}
          echo ${{ inputs.issue }}
          echo "${{ toJson(github) }}"
