name: Dispatch
on:
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest

    environment: prod
    steps:
      - uses: actions/checkout@v4
        with:
            ref: prod
      - run: |
          echo ${{ vars.DATA }}
          echo ${{ github.event.sender.login }}
          echo ${{ toJson(github) }}
