name: Label
on:
  issues:
    types:
      - labeled

permissions:
    actions: write

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - run: gh -R anuraaga/scratch workflow run _comment.yaml -r prod
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
