name: Label
on:
  issues:
    types:
      - labeled

jobs:
  apply:
    runs-on: ubuntu-latest

    environment: prod
    steps:
      - uses: actions/checkout@v4
        with:
            ref: prod
      - run: |
          echo ${{ vars.DATA }}
